// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    await api.crateApiSimpleInitApp();

                    
                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.13.0';

                  @override
                  int get rustContentHash => 1679604242;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'rust_lib_matrix_chat',
                    ioDirectory: 'rust/target/release/',
                    webPrefix: 'pkg/',
                    wasmBindgenName: 'wasm_bindgen',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<List<Message>> crateApiGetMessages({required String roomId });

Future<void> crateApiSimpleInitApp();

Future<List<RoomInfo>> crateApiListRooms();

Future<SessionInfo> crateApiLogin({required String homeserver , required String username , required String password , required String storePath , required String sessionPath });

Future<void> crateApiLogout({required String sessionPath });

Future<SessionInfo> crateApiRestoreSession({required String homeserver , required String storePath , required String sessionPath });

Future<void> crateApiSendMessage({required String roomId , required String text , String? replyToEventId });

Stream<SyncEvent> crateApiStartSync();


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<List<Message>> crateApiGetMessages({required String roomId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(roomId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_message,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiGetMessagesConstMeta,
            argValues: [roomId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiGetMessagesConstMeta => const TaskConstMeta(
            debugName: "get_messages",
            argNames: ["roomId"],
        );
        

@override Future<void> crateApiSimpleInitApp()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiSimpleInitAppConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
            debugName: "init_app",
            argNames: [],
        );
        

@override Future<List<RoomInfo>> crateApiListRooms()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_room_info,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiListRoomsConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiListRoomsConstMeta => const TaskConstMeta(
            debugName: "list_rooms",
            argNames: [],
        );
        

@override Future<SessionInfo> crateApiLogin({required String homeserver , required String username , required String password , required String storePath , required String sessionPath })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(homeserver, serializer);
sse_encode_String(username, serializer);
sse_encode_String(password, serializer);
sse_encode_String(storePath, serializer);
sse_encode_String(sessionPath, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiLoginConstMeta,
            argValues: [homeserver, username, password, storePath, sessionPath],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiLoginConstMeta => const TaskConstMeta(
            debugName: "login",
            argNames: ["homeserver", "username", "password", "storePath", "sessionPath"],
        );
        

@override Future<void> crateApiLogout({required String sessionPath })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionPath, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiLogoutConstMeta,
            argValues: [sessionPath],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiLogoutConstMeta => const TaskConstMeta(
            debugName: "logout",
            argNames: ["sessionPath"],
        );
        

@override Future<SessionInfo> crateApiRestoreSession({required String homeserver , required String storePath , required String sessionPath })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(homeserver, serializer);
sse_encode_String(storePath, serializer);
sse_encode_String(sessionPath, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiRestoreSessionConstMeta,
            argValues: [homeserver, storePath, sessionPath],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiRestoreSessionConstMeta => const TaskConstMeta(
            debugName: "restore_session",
            argNames: ["homeserver", "storePath", "sessionPath"],
        );
        

@override Future<void> crateApiSendMessage({required String roomId , required String text , String? replyToEventId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(roomId, serializer);
sse_encode_String(text, serializer);
sse_encode_opt_String(replyToEventId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiSendMessageConstMeta,
            argValues: [roomId, text, replyToEventId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiSendMessageConstMeta => const TaskConstMeta(
            debugName: "send_message",
            argNames: ["roomId", "text", "replyToEventId"],
        );
        

@override Stream<SyncEvent> crateApiStartSync()  { 
            final sink = RustStreamSink<SyncEvent>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_StreamSink_sync_event_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiStartSyncConstMeta,
            argValues: [sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateApiStartSyncConstMeta => const TaskConstMeta(
            debugName: "start_sync",
            argNames: ["sink"],
        );
        



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AnyhowException(raw as String); }

@protected RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
throw UnimplementedError(); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected PlatformInt64 dco_decode_i_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeI64(raw); }

@protected List<Message> dco_decode_list_message(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_message).toList(); }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected List<RoomInfo> dco_decode_list_room_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_room_info).toList(); }

@protected Message dco_decode_message(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
                return Message(eventId: dco_decode_String(arr[0]),
sender: dco_decode_String(arr[1]),
body: dco_decode_String(arr[2]),
timestampMillis: dco_decode_i_64(arr[3]),
replyToEventId: dco_decode_String(arr[4]),
replyToBody: dco_decode_String(arr[5]),); }

@protected String? dco_decode_opt_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_String(raw); }

@protected RoomInfo dco_decode_room_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return RoomInfo(roomId: dco_decode_String(arr[0]),
name: dco_decode_String(arr[1]),); }

@protected SessionInfo dco_decode_session_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return SessionInfo(userId: dco_decode_String(arr[0]),
displayName: dco_decode_String(arr[1]),); }

@protected SyncEvent dco_decode_sync_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
                return SyncEvent(kind: dco_decode_String(arr[0]),
roomId: dco_decode_String(arr[1]),
body: dco_decode_String(arr[2]),); }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_String(deserializer);
        return AnyhowException(inner); }

@protected RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
throw UnimplementedError('Unreachable ()'); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getPlatformInt64(); }

@protected List<Message> sse_decode_list_message(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <Message>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_message(deserializer)); }
        return ans_;
         }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected List<RoomInfo> sse_decode_list_room_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <RoomInfo>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_room_info(deserializer)); }
        return ans_;
         }

@protected Message sse_decode_message(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_eventId = sse_decode_String(deserializer);
var var_sender = sse_decode_String(deserializer);
var var_body = sse_decode_String(deserializer);
var var_timestampMillis = sse_decode_i_64(deserializer);
var var_replyToEventId = sse_decode_String(deserializer);
var var_replyToBody = sse_decode_String(deserializer);
return Message(eventId: var_eventId, sender: var_sender, body: var_body, timestampMillis: var_timestampMillis, replyToEventId: var_replyToEventId, replyToBody: var_replyToBody); }

@protected String? sse_decode_opt_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_String(deserializer));
            } else {
                return null;
            }
             }

@protected RoomInfo sse_decode_room_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_roomId = sse_decode_String(deserializer);
var var_name = sse_decode_String(deserializer);
return RoomInfo(roomId: var_roomId, name: var_name); }

@protected SessionInfo sse_decode_session_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_userId = sse_decode_String(deserializer);
var var_displayName = sse_decode_String(deserializer);
return SessionInfo(userId: var_userId, displayName: var_displayName); }

@protected SyncEvent sse_decode_sync_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_kind = sse_decode_String(deserializer);
var var_roomId = sse_decode_String(deserializer);
var var_body = sse_decode_String(deserializer);
return SyncEvent(kind: var_kind, roomId: var_roomId, body: var_body); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.message, serializer); }

@protected void sse_encode_StreamSink_sync_event_Sse(RustStreamSink<SyncEvent> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.setupAndSerialize(codec: SseCodec(
            decodeSuccessData: sse_decode_sync_event,
            decodeErrorData: sse_decode_AnyhowException,
        )), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putPlatformInt64(self); }

@protected void sse_encode_list_message(List<Message> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_message(item, serializer); } }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_list_room_info(List<RoomInfo> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_room_info(item, serializer); } }

@protected void sse_encode_message(Message self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.eventId, serializer);
sse_encode_String(self.sender, serializer);
sse_encode_String(self.body, serializer);
sse_encode_i_64(self.timestampMillis, serializer);
sse_encode_String(self.replyToEventId, serializer);
sse_encode_String(self.replyToBody, serializer);
 }

@protected void sse_encode_opt_String(String? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_String(self, serializer);
                }
                 }

@protected void sse_encode_room_info(RoomInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.roomId, serializer);
sse_encode_String(self.name, serializer);
 }

@protected void sse_encode_session_info(SessionInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.userId, serializer);
sse_encode_String(self.displayName, serializer);
 }

@protected void sse_encode_sync_event(SyncEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.kind, serializer);
sse_encode_String(self.roomId, serializer);
sse_encode_String(self.body, serializer);
 }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }
                }
                
